baseURL = "https://www.h4cklab.com/"
languageCode = 'zh'
DefaultContentLanguage = "zh" 
copyright = "转载请标注来源"
title = 'H4ck Lab'
theme = 'diary'
paginate = 9

contentdir = 'content'
[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4
[[menu.main]]
url = "https://114.h4cklab.com/"
name = "114"
weight = 5
[[menu.main]]
url = "https://1.writeups.cn/"
name = "WP"
weight = 6
[[menu.main]]
url = "mailto:i@domain.com"
name = "联系"
weight = 7


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 5

[params]
subtitle = "勇气力决心"
enableGitalk = false
enableGiscus = false

