baseURL = "https://www.h4cklab.com/"
languageCode = 'zh-cn'
title = 'H4ck Lab'
theme = 'diary'


[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4
[[menu.main]]
url = "https://114.h4cklab.com/"
name = "114"
weight = 5
[[menu.main]]
url = "https://1.writeups.cn/"
name = "WP"
weight = 6
